# Generated by Django 5.0.7 on 2024-07-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_created_at_remove_device_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='brand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
