# Generated by Django 5.0.7 on 2024-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='units',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
