# Generated by Django 5.0.7 on 2024-07-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='units',
            field=models.IntegerField(),
        ),
    ]
