# Generated by Django 5.0.7 on 2024-08-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='brand',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='device',
            name='units',
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(default='11'),
            preserve_default=False,
        ),
    ]
